namespace: naljal
name: s3-proxy

cluster-configs:
  configmaps:
    egov-config:
      data:
        s3-assets-bucket: "(naljal-uat-s3-egov-assets|egov-dev-assets)"

externalName: s3.ap-south-1.amazonaws.com
httpPort: 80
type: ExternalName