global:
  domain: ifix-uat.psegs.in
  containerRegistry: dwssio
  tracing-enabled: false
  namespace: pspcl
  nodepool:
    selector: ifix-uat-ng
    toleration: ifix-uat-ng

cluster-configs:
  namespaces:
    create: false
    values:
      [ 
        ifix, 
        cert-manager,
        olap,
        pspcl
      ]

  rbac:
    - role: user
      namespaces: [pspcl]
    - role: admin
      namespaces: [pspcl]

  root-ingress:
    cert-issuer: letsencrypt-prod
  configmaps:
    egov-config:
      data:
        mongo-db-host: "ifix-db.cluster-cqqfmghbjssw.ap-south-1.docdb.amazonaws.com"
        mongo-db-name: "pspcl_qa_db"
        mongo-db-url: "mongodb://ifix-db.cluster-cqqfmghbjssw.ap-south-1.docdb.amazonaws.com:27017/?retryWrites=false"
        db-host: "magramsewa-uat-db.cvisvjyknxm1.ap-south-1.rds.amazonaws.com"
        db-name: "mgramseva_uat_db"
        keycloak-db-name: "keycloak_uat_db"
        db-url: "jdbc:postgresql://magramsewa-uat-db.cvisvjyknxm1.ap-south-1.rds.amazonaws.com:5432/mgramseva_uat_db"
        domain: "ifix-uat.psegs.in"
        egov-services-fqdn-name: "ifix-uat.psegs.in/"
        egov-state-level-tenant-id: "pb"
        flyway-locations: "filesystem:/flyway/sql,filesystem:/flyway/seed,filesystem:/flyway/uat"
        kafka-brokers: "kafka-v2.pspcl:9092"
        kafka-infra-brokers: "kafka-v2-infra.pspcl:9092"
        logging-level-jdbc: "debug"
        serializers-timezone-in-ist: "true"
        server-tomcat-max-threads: "10"
        server-tomcat-max-connections: "500"
        spring-datasource-tomcat-initialSize: "1"
        spring-datasource-tomcat-max-active: "5"
        spring-jpa-show-sql: "true"
        tracer-errors-provideexceptionindetails: "true"
        timezone: "Asia/Kolkata"
        druid-host: "druid-broker.olap"

    egov-service-host:
      data:
        ifix-master-data-service: "http://ifix-master-data-service.ifix:8080/"
        fiscal-event-service: "http://fiscal-event-service.ifix:8080/"
        ifix-zuul: "http://ifix-zuul.ifix:8080/"
        ifix-department-entity-service: "http://ifix-department-entity-service.ifix:8080/"
        egov-mdms-service: "https://mgramseva-uat.psegs.in/"
      


postgres:
  persistence:
    enabled: true
    azure:
      diskName: "postgres-db-0"  
      diskUri: /subscriptions/71f67180-c7fb-43dd-988a-e9f9e3135adc/resourceGroups/MC_mgramsewa-qa_mgramsewa-qa_southeastasia/providers/Microsoft.Compute/disks/postgres-db-0
  postgresDatabase: mgramseva_qa_db

pspcl-ifix-adapter:
  pspcl-fetch-bill-url: "https://billapp.pspcl.in//fetchbillingdata.asmx"
  pspcl-fetch-payment-url: "https://billapp.pspcl.in//fetchbillingdata.asmx"
  keycloak-pspcl-credentials-clientid: "pspcl-ifix-uat"
  fiscal-event-tenantId: "pb"
  demand-coaCode: "8247-12-373-56-78-90"
  receipt-coaCode: "8247-12-373-56-78-90"
  fiscal-event-receiver: "mgramseva-uat"
  ifix-host: "https://ifix-uat.psegs.in/"
  keycloak-host: "https://ifix-uat.psegs.in/"
  java-enable-debug: "true"
