# Common Labels
labels:
  app: "pspcl-ifix-adapter"
  group: "pspcl"

cron:
  schedule: "0 0 * * *"  

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    image:
      repository: "pspcl-ifix-adapter-db"

# Container Configs
image:
  repository: "pspcl-ifix-adapter"

cron_appType: "java-spring"
dbMigration:
  schemaTable: "pspcl_ifix_adapter_schema"


# Additional Container Envs
env: |
  - name: PSPCL_FETCH_BILL_URL
    value: {{ index .Values "pspcl-fetch-bill-url" | quote }}
  - name: PSPCL_FETCH_PAYMENT_URL
    value: {{ index .Values "pspcl-fetch-payment-url" | quote }}
  - name: IFIX_HOST
    value: {{ index .Values "ifix-host" | quote }}
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: KEYCLOAK_HOST
    value: {{ index .Values "keycloak-host" | quote }}
  - name: KEYCLOAK_CREDENTIALS_CLIENTID
    value: {{ index .Values "keycloak-pspcl-credentials-clientid" | quote }}
  - name: KEYCLOAK_CREDENTIALS_CLIENTSECRET
    valueFrom:
      secretKeyRef:
        name: keycloak-client-secrets
        key: pspcl-keycloak-client-secret
  - name: FISCAL_EVENT_TENANTID
    value: {{ index .Values "fiscal-event-tenantId" | quote }}
  - name: DEMAND_COACODE  
    value: {{ index .Values "demand-coaCode" | quote }} 
  - name: RECEIPT_COACODE
    value: {{ index .Values "receipt-coaCode" | quote }}
  - name: FISCAL_EVENT_RECEIVER  
    value: {{ index .Values "fiscal-event-receiver" | quote }}
  
